---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.74.76
      ansible_user: centos
      ansible_python_interpreter: /usr/bin/python2.7
      ansible_ssh_private_key_file: /home/alex/.ssh/terra_new_key
vector:
  hosts:
    vector-01:
      ansible_host: 158.160.99.102
      ansible_user: centos
      ansible_python_interpreter: /usr/bin/python2.7
      ansible_ssh_private_key_file: /home/alex/.ssh/terra_new_key
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 158.160.104.147
      ansible_user: centos
      ansible_python_interpreter: /usr/bin/python2.7
      ansible_ssh_private_key_file: /home/alex/.ssh/terra_new_key