---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.68.163 
      ansible_user: centos
      ansible_python_interpreter: /usr/bin/python2.7
      ansible_ssh_private_key_file: /home/alex/.ssh/terra_new_key
vector:
  hosts:
    vector-01:
      ansible_host: 158.160.32.189
      ansible_user: centos
      ansible_python_interpreter: /usr/bin/python2.7
      ansible_ssh_private_key_file: /home/alex/.ssh/terra_new_key
